# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 14:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milo_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='random_number',
            field=models.PositiveIntegerField(default=74, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
